const CONFIG = require('../Main_file');
// src/controllers/employeeImportController.js
// Bulk import new employees from the Excel template
const db     = require('../config/db');
const bcrypt = require('bcryptjs');
const XLSX   = require('xlsx');
const multer = require('multer');

exports.uploadMiddleware = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 10 * 1024 * 1024 },
  fileFilter: (req, file, cb) => {
    if (/\.(xlsx|xls)$/.test(file.originalname.toLowerCase())) cb(null, true);
    else cb(new Error('Only Excel files allowed'));
  }
}).single('file');

// Column mapping from our Excel template (0-indexed) — matches the headers
// generated by exports.downloadImportTemplate below, in the same order.
// Department/Designation are entered by NAME (auto-created if new — see
// findOrCreateDept/findOrCreateDesignation) and Reporting Manager/Team Leader
// by EMPLOYEE CODE (resolved to an id — never a raw numeric DB id, which HR
// has no way of knowing when filling the sheet).
const COL = {
  employee_code: 0, password: 1, first_name: 2, last_name: 3,
  email: 4, phone: 5, alternate_phone: 6, gender: 7, date_of_birth: 8,
  blood_group: 9, marital_status: 10,
  department: 11, designation: 12, role: 13, employee_category: 14, level: 15,
  joining_date: 16, employment_type: 17, saturday_policy: 18, probation_end_date: 19,
  reporting_manager_code: 20, team_leader_code: 21,
  pan_number: 22, aadhar_number: 23, uan_number: 24, pf_number: 25,
  bank_name: 26, bank_branch: 27, bank_account: 28, bank_ifsc: 29,
  address_line1: 30, city: 31, state: 32, pincode: 33, present_state_code: 34,
  permanent_address: 35, permanent_state: 36, permanent_state_code: 37,
  nationality: 38, father_name: 39, spouse_name: 40, no_of_children: 41,
  place_of_birth: 42, personal_mobile: 43, personal_email: 44,
  emergency_contact_name: 45, emergency_contact_phone: 46,
  location: 47, branch: 48, division: 49, pt_state: 50, notes: 51,
  // ── Salary Structure — matches Edit Employee > Salary Structure tab exactly.
  // Written into employee_salary_structure (the real source of truth for
  // payroll/payslip), not just the legacy employees.basic_salary columns.
  sal_basic: 52, sal_hra: 53, sal_conveyance: 54, sal_defray_allowance: 55,
  sal_gratuity: 56, sal_food_coupon: 57,
  sal_pf_applicable: 58, sal_pf_wage_basis: 59, sal_esi_applicable: 60,
  sal_pt_applicable: 61, sal_lwf_applicable: 62, sal_tds_applicable: 63
};

// ── Find-or-create helpers (Department/Designation may be brand new) ────────
async function findOrCreateDept(client, name, cache) {
  if (!name) return null;
  const key = name.trim().toLowerCase();
  if (cache.has(key)) return cache.get(key);
  const found = await client.query(`SELECT id FROM departments WHERE LOWER(TRIM(name))=$1`, [key]);
  let id;
  if (found.rows.length) id = found.rows[0].id;
  else {
    const ins = await client.query(`INSERT INTO departments(name) VALUES($1) RETURNING id`, [name.trim()]);
    id = ins.rows[0].id;
  }
  cache.set(key, id);
  return id;
}

async function findOrCreateDesignation(client, title, departmentId, cache) {
  if (!title) return null;
  const key = title.trim().toLowerCase();
  if (cache.has(key)) return cache.get(key);
  const found = await client.query(`SELECT id FROM designations WHERE LOWER(TRIM(title))=$1`, [key]);
  let id;
  if (found.rows.length) id = found.rows[0].id;
  else {
    const ins = await client.query(
      `INSERT INTO designations(title, department_id) VALUES($1,$2) RETURNING id`,
      [title.trim(), departmentId || null]
    );
    id = ins.rows[0].id;
  }
  cache.set(key, id);
  return id;
}

function clean(val) {
  return val !== null && val !== undefined && val !== '' ? String(val).trim() : null;
}

// Handles 'YYYY-MM-DD' strings, other parseable date strings, AND raw Excel
// serial date numbers (e.g. 45900) — which XLSX sometimes hands back as plain
// numbers when a cell is formatted as a date but read without cellDates:true.
// IMPORTANT: only numbers inside a plausible date-serial range are treated as
// serials. Blindly treating any numeric-looking value as a serial (the old
// behaviour here) silently turned blank/junk cells into garbage dates near
// 1970-01-01 or 1899-12-30 — which is exactly the bug that produced bogus
// "01 Jan 1970" joining dates on imported/re-uploaded employee records.
// NOTE: this is shared by date_of_birth too, so it must NOT reject old dates
// outright (people born before 1980 are real) — the "is this suspiciously
// ancient for a JOINING date" check lives separately, in toJoiningDate() below.
function toDate(val) {
  if (!val) return null;
  const s = String(val).trim();
  if (!s) return null;
  if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return s;
  if (/^-?\d+(\.\d+)?$/.test(s)) {
    const serial = parseFloat(s);
    // Plausible Excel date-serial range (~1954–2146). Anything outside this
    // is not a real date serial — fall through to null rather than guessing.
    if (serial > 20000 && serial < 90000) {
      const d = new Date(Math.round((serial - 25569) * 86400 * 1000));
      return isNaN(d.getTime()) ? null : d.toISOString().split('T')[0];
    }
    return null;
  }
  const d = new Date(s);
  if (!isNaN(d.getTime())) return d.toISOString().split('T')[0];
  return null;
}

// Joining date specifically: on top of toDate()'s parsing, reject anything
// that lands before 1980. No current employee joined this company before it
// existed — a pre-1980 result here is always a placeholder/typo/blank-cell
// artifact ("01/01/1970" etc.), never a real joining date. Use this (not the
// bare toDate()) wherever a JOINING date is parsed from an import file.
function toJoiningDate(val) {
  const d = toDate(val);
  return (d && d.slice(0, 4) > '1980') ? d : null;
}

function toNum(val) {
  const n = parseFloat(val);
  return isNaN(n) ? 0 : n;
}

exports.importEmployees = async (req, res) => {
  if (!req.file)
    return res.status(400).json({ success: false, message: 'Excel file required' });

  const client = await db.getClient();
  try {
    await client.query('BEGIN');

    const wb = XLSX.read(req.file.buffer, { type: 'buffer' });
    console.log(`[Import] Sheet names in uploaded file: ${wb.SheetNames.join(', ')}`);
    const ws = wb.Sheets['Employee Import'] || wb.Sheets[wb.SheetNames[0]];
    const rows = XLSX.utils.sheet_to_json(ws, { header: 1, defval: '' });
    console.log(`[Import] Total rows read from sheet: ${rows.length}`);
    console.log(`[Import] Row 3 (header, 0-indexed):`, rows[2]);
    console.log(`[Import] Row 4 (first data row, 0-indexed):`, rows[4]);

    // Skip title row (1) + header row (2) + hint row (3) = start at index 3
    const dataRows = rows.slice(3).filter(r => {
      const code = clean(r[COL.employee_code]);
      return code && !code.toLowerCase().startsWith('emp code') && !code.toLowerCase().startsWith('kcms00')
        && !code.toUpperCase().includes('SAMPLE');
    });
    console.log(`[Import] Data rows after filter: ${dataRows.length}`);

    if (!dataRows.length)
      return res.status(400).json({ success: false, message: 'No data rows found (delete sample rows first)' });

    const results = { imported: [], skipped: [], errors: [] };
    const deptCache = new Map();
    const desigCache = new Map();

    // Employee-code -> id, refreshed as new rows are inserted so a manager
    // and their report can appear in the same sheet in any order.
    const codeToId = new Map();
    const existingCodes = await client.query(`SELECT id, employee_code FROM employees`);
    existingCodes.rows.forEach(r => codeToId.set((r.employee_code || '').toUpperCase(), r.id));

    for (let i = 0; i < dataRows.length; i++) {
      const row = dataRows[i];
      const rowNum = i + 4; // Excel row number for reporting

      const employee_code = clean(row[COL.employee_code])?.toUpperCase();
      const first_name    = clean(row[COL.first_name]);
      const email         = clean(row[COL.email])?.toLowerCase();
      const pan_for_pwd   = clean(row[COL.pan_number]);
      const password      = clean(row[COL.password]) || pan_for_pwd || `${CONFIG.defaultImportPassword}`;

      // Required field validation
      if (!employee_code) { results.errors.push(`Row ${rowNum}: employee_code is required`); continue; }
      if (!first_name)    { results.errors.push(`Row ${rowNum}: first_name is required`); continue; }
      if (!email)         { results.errors.push(`Row ${rowNum}: email is required`); continue; }
      if (password.length < 8) { results.errors.push(`Row ${rowNum}: password must be at least 8 characters`); continue; }

      // Check duplicates
      const dupCheck = await client.query(
        `SELECT id FROM employees WHERE UPPER(employee_code)=$1 OR LOWER(email)=$2`,
        [employee_code, email]
      );
      if (dupCheck.rows.length) {
        results.skipped.push(`Row ${rowNum}: ${employee_code} / ${email} already exists`);
        continue;
      }

      const hash = await bcrypt.hash(password, 10);
      const role_val = clean(row[COL.role]) || 'employee';
      const valid_roles = ['employee','tl','manager','hr','accounts','admin'];
      const role = valid_roles.includes(role_val) ? role_val : 'employee';

      try {
        // Savepoint per row: if a single row's INSERT fails (bad data, FK
        // violation, etc.) we roll back just that row instead of poisoning
        // the whole transaction and aborting every subsequent row.
        await client.query('SAVEPOINT row_import');

        // Department/Designation entered by NAME — auto-created if this is
        // a brand new one that doesn't exist in the system yet.
        const deptName  = clean(row[COL.department]);
        const desigName = clean(row[COL.designation]);
        const departmentId   = await findOrCreateDept(client, deptName, deptCache);
        const designationId  = await findOrCreateDesignation(client, desigName, departmentId, desigCache);

        // Reporting Manager / Team Leader entered by EMPLOYEE CODE — resolved
        // to an id. Not found = left blank (never blocks the row).
        const mgrCode = clean(row[COL.reporting_manager_code])?.toUpperCase();
        const tlCode  = clean(row[COL.team_leader_code])?.toUpperCase();
        const managerId = mgrCode ? (codeToId.get(mgrCode) || null) : null;
        const tlId       = tlCode  ? (codeToId.get(tlCode)  || null) : null;
        if (mgrCode && !managerId) results.errors.push(`Row ${rowNum}: Reporting Manager code "${mgrCode}" not found — left blank`);
        if (tlCode  && !tlId)      results.errors.push(`Row ${rowNum}: Team Leader code "${tlCode}" not found — left blank`);

        const category_val = clean(row[COL.employee_category]) || 'permanent';
        const satPolicy_val = clean(row[COL.saturday_policy]) === 'all_working' ? 'all_working' : '2nd_4th_off';

        const result = await client.query(
          `INSERT INTO employees (
             employee_code, first_name, last_name, email, phone, alternate_phone,
             gender, date_of_birth, blood_group, marital_status, joining_date,
             employment_type, employee_category, level, saturday_policy, role, password_hash,
             department_id, designation_id, reporting_manager_id, team_leader_id,
             basic_salary, hra, special_allowance, travel_allowance, ctc,
             pan_number, aadhar_number, uan_number, pf_number,
             bank_name, bank_account, bank_ifsc, bank_branch,
             address_line1, city, state, pincode, present_state_code,
             permanent_address, permanent_state, permanent_state_code,
             nationality, father_name, spouse_name, no_of_children, place_of_birth,
             personal_mobile, personal_email,
             emergency_contact_name, emergency_contact_phone,
             location, branch, division, pt_state, notes,
             probation_end_date, is_active
           ) VALUES (
             $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,
             $22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,
             $35,$36,$37,$38,$39,$40,$41,$42,$43,$44,$45,$46,$47,$48,$49,$50,$51,$52,$53,$54,$55,true
           ) RETURNING id, employee_code, first_name, last_name, email`,
          [
            employee_code,
            first_name,
            clean(row[COL.last_name]) || '',
            email,
            clean(row[COL.phone]),
            clean(row[COL.alternate_phone]),
            clean(row[COL.gender]),
            toDate(row[COL.date_of_birth]),
            clean(row[COL.blood_group]),
            clean(row[COL.marital_status]),
            toJoiningDate(row[COL.joining_date]) || new Date().toISOString().split('T')[0],
            clean(row[COL.employment_type]) || 'Full-Time',
            category_val,
            clean(row[COL.level]),
            satPolicy_val,
            role,
            hash,
            departmentId,
            designationId,
            managerId,
            tlId,
            // Salary fields are not collected here — set via the payroll module after import.
            0, 0, 0, 0, 0,
            clean(row[COL.pan_number])?.toUpperCase(),
            clean(row[COL.aadhar_number]),
            clean(row[COL.uan_number]),
            clean(row[COL.pf_number]),
            clean(row[COL.bank_name]),
            clean(row[COL.bank_account]),
            clean(row[COL.bank_ifsc])?.toUpperCase(),
            clean(row[COL.bank_branch]),
            clean(row[COL.address_line1]),
            clean(row[COL.city]),
            clean(row[COL.state]),
            clean(row[COL.pincode]),
            clean(row[COL.present_state_code]),
            clean(row[COL.permanent_address]),
            clean(row[COL.permanent_state]),
            clean(row[COL.permanent_state_code]),
            clean(row[COL.nationality]) || 'Indian',
            clean(row[COL.father_name]),
            clean(row[COL.spouse_name]),
            parseInt(row[COL.no_of_children]) || null,
            clean(row[COL.place_of_birth]),
            clean(row[COL.personal_mobile]),
            clean(row[COL.personal_email])?.toLowerCase(),
            clean(row[COL.emergency_contact_name]),
            clean(row[COL.emergency_contact_phone]),
            clean(row[COL.location]),
            clean(row[COL.branch]),
            clean(row[COL.division]),
            clean(row[COL.pt_state]),
            clean(row[COL.notes]),
            toDate(row[COL.probation_end_date]),
          ]
        );

        const newEmp = result.rows[0];
        codeToId.set(employee_code, newEmp.id);
        results.imported.push({
          employee_code: newEmp.employee_code,
          name: `${newEmp.first_name} ${newEmp.last_name}`,
          email: newEmp.email
        });

        // Auto-seed leave balances based on joining date
        // Rule: < 6 months from today → PL=6 only
        //       >= 6 months → EL=18, CL=6, SL=6
        {
          const currentYear = new Date().getFullYear();
          const today = new Date();
          const empJoiningDate = new Date(toJoiningDate(row[COL.joining_date]) || new Date());
          const sixMonthMark = new Date(empJoiningDate);
          sixMonthMark.setMonth(sixMonthMark.getMonth() + 6);
          const isUnderSixMonths = today < sixMonthMark;

          const ltRes = await client.query(
            `SELECT id, code FROM leave_types WHERE is_active=true AND code IN ('EL','CL','SL','PL')`
          );
          const ltMap = {};
          for (const lt of ltRes.rows) ltMap[lt.code] = lt.id;

          if (isUnderSixMonths) {
            // Under 6 months: PL = 6 upfront
            if (ltMap['PL']) {
              await client.query(
                `INSERT INTO leave_balances(employee_id,leave_type_id,year,allocated,used,pending,carry_forward)
                 VALUES($1,$2,$3,6,0,0,0) ON CONFLICT DO NOTHING`,
                [newEmp.id, ltMap['PL'], currentYear]
              );
            }
          } else {
            // 6+ months: full EL/CL/SL — EL=18, CL=6, SL=6
            const allocations = { EL: 18, CL: 6, SL: 6 };
            for (const [code, alloc] of Object.entries(allocations)) {
              if (ltMap[code]) {
                await client.query(
                  `INSERT INTO leave_balances(employee_id,leave_type_id,year,allocated,used,pending,carry_forward)
                   VALUES($1,$2,$3,$4,0,0,0) ON CONFLICT DO NOTHING`,
                  [newEmp.id, ltMap[code], currentYear, alloc]
                );
              }
            }
          }
        }

        const payCtrl = require('./payrollController');
        // Salary Structure — only written if the sheet actually has a Basic
        // Salary for this row (imports of legacy/inactive-payroll employees
        // often leave this blank on purpose, to be set later via Payroll).
        const salBasic = parseFloat(clean(row[COL.sal_basic]));
        if (salBasic > 0) {
          const yn = (v) => { const s = clean(v)?.toUpperCase(); return s === 'Y' || s === 'YES' || s === 'TRUE'; };
          await payCtrl.computeAndSaveSalaryStructure(client, newEmp.id, {
            basic:             salBasic,
            hra:               parseFloat(clean(row[COL.sal_hra])) || 0,
            conveyance:        parseFloat(clean(row[COL.sal_conveyance])) || 0,
            special_allowance: parseFloat(clean(row[COL.sal_defray_allowance])) || 0,
            gratuity:          parseFloat(clean(row[COL.sal_gratuity])) || 0,
            food_coupon:       parseFloat(clean(row[COL.sal_food_coupon])) || 0,
            pf_applicable:     yn(row[COL.sal_pf_applicable]),
            pf_wage_basis:     clean(row[COL.sal_pf_wage_basis])?.toLowerCase() === 'actual' ? 'actual' : 'capped',
            esi_applicable:    yn(row[COL.sal_esi_applicable]),
            pt_applicable:     yn(row[COL.sal_pt_applicable]),
            lwf_applicable:    yn(row[COL.sal_lwf_applicable]),
            tds_applicable:    yn(row[COL.sal_tds_applicable])
          }, req.user.id);
        }

        // Seed onboarding tracker steps
        const onboardCtrl = require('./onboardingController');
        await onboardCtrl.seedForEmployee(newEmp.id, client);

        await client.query('RELEASE SAVEPOINT row_import');

      } catch (rowErr) {
        await client.query('ROLLBACK TO SAVEPOINT row_import');
        results.errors.push(`Row ${rowNum} (${employee_code}): ${rowErr.message}`);
      }
    }

    await client.query('COMMIT');
    console.log(`[Import] Done: ${results.imported.length} imported, ${results.skipped.length} skipped, ${results.errors.length} errors`);
    if (results.errors.length) console.log('[Import] Errors:', results.errors);
    if (results.skipped.length) console.log('[Import] Skipped:', results.skipped);
    res.json({
      success: true,
      message: `Import complete: ${results.imported.length} imported, ${results.skipped.length} skipped, ${results.errors.length} errors`,
      data: {
        imported: results.imported,
        skipped:  results.skipped,
        errors:   results.errors.slice(0, 50),
        summary: {
          total_rows: dataRows.length,
          imported: results.imported.length,
          skipped:  results.skipped.length,
          errors:   results.errors.length
        }
      }
    });
  } catch (err) {
    await client.query('ROLLBACK');
    console.error(err);
    res.status(500).json({ success: false, message: 'Server error: ' + err.message });
  } finally { client.release(); }
};

// ── Master Information Report update ─────────────────────────────────────────
// Reads the "Master_Information_Report.xlsx" layout and bulk-updates existing
// employees (matched by Employee ID / employee_code) with all the fields that
// the standard import template doesn't carry.
const MASTER_COL = {
  employee_code: 0,  // "Employee ID"
  employee_name: 1,  // "Employee Name" (split into first+last)
  location:      2,
  branch:        3,
  branch_effective_date: 4,
  designation:   5,
  division:      6,
  joining_date:  7,
  date_of_birth: 8,
  reporting_officer: 9,
  department:   10,
  email:        11,
  phone:        12,
  uan_number:   13,
  pan_number:   14,
  aadhar_number:15,
  pf_number:    16,
  status:       17,
  gender:       18,
  father_name:  19,
  personal_mobile: 20,
  personal_email:  21,
  place_of_birth:  22,
  nationality:     23,
  marital_status:  24,
  spouse_name:     25,
  no_of_children:  26,
  present_address: 27,
  present_state:   28,
  present_state_code: 29,
  permanent_address:  30,
  permanent_state:    31,
  permanent_state_code: 32,
  blood_group:     33,
  emergency_contact_name:  34,
  emergency_contact_phone: 35,
  pt_state:        36,
};

exports.masterUpdate = async (req, res) => {
  if (!req.file)
    return res.status(400).json({ success: false, message: 'Excel file required' });

  const client = await db.getClient();
  try {
    await client.query('BEGIN');

    const wb = XLSX.read(req.file.buffer, { type: 'buffer' });
    const ws = wb.Sheets[wb.SheetNames[0]];
    const rows = XLSX.utils.sheet_to_json(ws, { header: 1, defval: '' });

    const dataRows = rows.slice(1).filter(r => {
      const code = clean(r[MASTER_COL.employee_code]);
      return code && code.length > 0;
    });

    if (!dataRows.length)
      return res.status(400).json({ success: false, message: 'No data rows found' });

    const results = { updated: [], skipped: [], errors: [] };

    for (let i = 0; i < dataRows.length; i++) {
      const row = dataRows[i];
      const rowNum = i + 2;
      const empCode = clean(row[MASTER_COL.employee_code])?.toUpperCase();
      if (!empCode) { results.skipped.push(`Row ${rowNum}: no employee code`); continue; }

      try {
        await client.query('SAVEPOINT master_row');

        const existing = await client.query(
          `SELECT id FROM employees WHERE UPPER(employee_code) = $1`, [empCode]
        );
        if (!existing.rows.length) {
          results.skipped.push(`Row ${rowNum}: ${empCode} not found`);
          await client.query('RELEASE SAVEPOINT master_row');
          continue;
        }
        const empId = existing.rows[0].id;

        const nameParts = (clean(row[MASTER_COL.employee_name]) || '').split(/\s+/);
        const firstName = nameParts[0] || null;
        const lastName = nameParts.slice(1).join(' ') || null;

        // Strip spaces from Aadhaar for DB storage
        const rawAadhaar = clean(row[MASTER_COL.aadhar_number]);
        const aadhaar = rawAadhaar ? rawAadhaar.replace(/\s+/g, '') : null;

        const updates = {
          location:         clean(row[MASTER_COL.location]),
          branch:           clean(row[MASTER_COL.branch]),
          branch_effective_date: toDate(row[MASTER_COL.branch_effective_date]),
          division:         clean(row[MASTER_COL.division]),
          gender:           clean(row[MASTER_COL.gender]),
          father_name:      clean(row[MASTER_COL.father_name]),
          personal_mobile:  clean(row[MASTER_COL.personal_mobile]),
          personal_email:   clean(row[MASTER_COL.personal_email]),
          place_of_birth:   clean(row[MASTER_COL.place_of_birth]),
          nationality:      clean(row[MASTER_COL.nationality]),
          marital_status:   clean(row[MASTER_COL.marital_status]),
          spouse_name:      clean(row[MASTER_COL.spouse_name]),
          no_of_children:   row[MASTER_COL.no_of_children] !== '' ? parseInt(row[MASTER_COL.no_of_children]) : null,
          address_line1:    clean(row[MASTER_COL.present_address]),
          state:            clean(row[MASTER_COL.present_state]),
          present_state_code: clean(row[MASTER_COL.present_state_code]),
          permanent_address:    clean(row[MASTER_COL.permanent_address]),
          permanent_state:      clean(row[MASTER_COL.permanent_state]),
          permanent_state_code: clean(row[MASTER_COL.permanent_state_code]),
          blood_group:      clean(row[MASTER_COL.blood_group]),
          emergency_contact_name:  clean(row[MASTER_COL.emergency_contact_name]),
          emergency_contact_phone: clean(row[MASTER_COL.emergency_contact_phone]),
          pt_state:         clean(row[MASTER_COL.pt_state]),
          uan_number:       clean(row[MASTER_COL.uan_number]),
          pan_number:       clean(row[MASTER_COL.pan_number])?.toUpperCase(),
          aadhar_number:    aadhaar,
          pf_number:        clean(row[MASTER_COL.pf_number]),
          phone:            clean(row[MASTER_COL.phone]),
          date_of_birth:    toDate(row[MASTER_COL.date_of_birth]),
          joining_date:     toJoiningDate(row[MASTER_COL.joining_date]),
        };

        if (firstName) updates.first_name = firstName;
        if (lastName) updates.last_name = lastName;

        // Filter out NaN values from parseInt
        const sets = [], params = [];
        let idx = 1;
        for (const [key, val] of Object.entries(updates)) {
          if (val !== null && val !== undefined && !(typeof val === 'number' && isNaN(val))) {
            sets.push(`${key}=$${idx++}`);
            params.push(val);
          }
        }

        if (sets.length) {
          sets.push(`updated_at=NOW()`);
          params.push(empId);
          await client.query(
            `UPDATE employees SET ${sets.join(',')} WHERE id=$${idx}`, params
          );
          results.updated.push(`${empCode}`);
        } else {
          results.skipped.push(`Row ${rowNum}: ${empCode} — no data to update`);
        }

        await client.query('RELEASE SAVEPOINT master_row');
      } catch (rowErr) {
        await client.query('ROLLBACK TO SAVEPOINT master_row');
        results.errors.push(`Row ${rowNum} (${empCode}): ${rowErr.message}`);
      }
    }

    await client.query('COMMIT');
    res.json({
      success: true,
      message: `Master update: ${results.updated.length} updated, ${results.skipped.length} skipped, ${results.errors.length} errors`,
      data: {
        updated: results.updated,
        skipped: results.skipped,
        errors: results.errors.slice(0, 50),
        summary: {
          total_rows: dataRows.length,
          updated: results.updated.length,
          skipped: results.skipped.length,
          errors: results.errors.length
        }
      }
    });
  } catch (err) {
    await client.query('ROLLBACK');
    console.error(err);
    res.status(500).json({ success: false, message: 'Server error: ' + err.message });
  } finally { client.release(); }
};

// Generate the Employee Import template on the fly, so it always matches the
// COL mapping this controller actually parses (no more stale/missing static
// file). Layout: Row1 title, Row2 headers, Row3 sample/hint row (filtered out
// on import because its employee_code starts with "kcms00"), Row4+ blank for
// data — matches the "title+header+hint = start at index 3" logic above.
// A second sheet lists Department/Designation/Employee IDs for lookup.
exports.downloadImportTemplate = async (req, res) => {
  try {
    // Column order MUST match COL above exactly. Department/Designation are
    // entered by NAME (auto-created if new) and Reporting Manager/Team Leader
    // by EMPLOYEE CODE — never raw numeric DB ids, which HR has no way of
    // knowing while filling the sheet.
    const HEADERS = [
      'Employee Code*', 'Password (optional)', 'First Name*', 'Last Name',
      'Email*', 'Phone', 'Alternate Phone', 'Gender', 'Date of Birth (YYYY-MM-DD)',
      'Blood Group', 'Marital Status',
      'Department', 'Designation', 'Role', 'Category', 'Level',
      'Joining Date (YYYY-MM-DD)', 'Employment Type', 'Saturday Policy (2nd_4th_off/all_working)', 'Probation End Date (YYYY-MM-DD)',
      'Reporting Manager (Emp Code)', 'Team Leader (Emp Code)',
      'PAN Number', 'Aadhar Number', 'UAN Number', 'PF Number',
      'Bank Name', 'Bank Branch', 'Bank Account', 'Bank IFSC',
      'Address Line 1', 'City', 'State', 'Pincode', 'Present State Code',
      'Permanent Address', 'Permanent State', 'Permanent State Code',
      'Nationality', 'Father Name', 'Spouse Name', 'No. of Children', 'Place of Birth',
      'Personal Mobile', 'Personal Email',
      'Emergency Contact Name', 'Emergency Contact Phone',
      'Location', 'Branch', 'Division', 'PT State', 'Notes',
      'Basic Salary (₹/month)', 'HRA (₹/month)', 'Conveyance (₹/month)', 'Defray Allowance (₹/month)',
      'Gratuity (₹/month)', 'Food Coupon (₹/month)',
      'PF Applicable (Y/N)', 'PF Wage Basis (capped/actual)', 'ESI Applicable (Y/N)',
      'PT Applicable (Y/N)', 'LWF Applicable (Y/N)', 'TDS Applicable (Y/N)'
    ];

    // A real employee (whichever exists) as a fill-in-the-blank example, so
    // HR sees the expected format rather than guessing — never written back
    // if this row is left in the sheet by mistake (Emp Code will already
    // exist, so the import simply skips it as a duplicate).
    const sampleRes = await db.query(`
      SELECT e.employee_code, e.first_name, e.last_name, e.email, e.phone, e.gender,
             d.name AS department, des.title AS designation, e.role,
             e.employee_category, e.level, e.employment_type,
             COALESCE(e.saturday_policy,'2nd_4th_off') AS saturday_policy,
             m.employee_code AS manager_code, tl.employee_code AS tl_code,
             e.city, e.state
      FROM employees e
      LEFT JOIN departments d ON e.department_id = d.id
      LEFT JOIN designations des ON e.designation_id = des.id
      LEFT JOIN employees m ON e.reporting_manager_id = m.id
      LEFT JOIN employees tl ON e.team_leader_id = tl.id
      WHERE e.is_active = true
      ORDER BY e.id LIMIT 1`);
    const ex = sampleRes.rows[0] || {};

    const sampleRow = [
      'E999 (SAMPLE — DELETE THIS ROW)', '', 'John', 'Doe',
      'john.doe@example.com', '9999999999', '', 'Male', '1995-01-15',
      'O+', 'Single',
      ex.department || 'Operations', ex.designation || 'Executive', ex.role || 'employee', ex.employee_category || 'permanent', ex.level || 'L1',
      '2026-01-01', ex.employment_type || 'Full-Time', ex.saturday_policy || '2nd_4th_off', '',
      ex.manager_code || '', ex.tl_code || '',
      '', '', '', '',
      '', '', '', '',
      '', ex.city || '', ex.state || '', '', '',
      '', '', '',
      'Indian', '', '', '', '',
      '', '',
      '', '',
      '', '', '', '', '',
      '', '', '', '',
      '', '',
      'Y', 'capped', 'N',
      'Y', 'N', 'N'
    ];

    const rows = [
      [`HRMS — Employee Import Template  (Roles: employee, tl, manager, hr, accounts, admin)`],
      [`⚠️  Department/Designation: type the NAME — a new one is created automatically if it doesn't exist yet. Reporting Manager/Team Leader: type their EMPLOYEE CODE (must already exist). Delete the sample row before uploading.`],
      HEADERS,
      sampleRow
    ];

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(rows);
    ws['!cols'] = HEADERS.map(() => ({ wch: 20 }));
    ws['!merges'] = [
      { s: { r: 0, c: 0 }, e: { r: 0, c: HEADERS.length - 1 } },
      { s: { r: 1, c: 0 }, e: { r: 1, c: HEADERS.length - 1 } },
    ];
    XLSX.utils.book_append_sheet(wb, ws, 'Employee Import');

    // Reference sheet — existing Department/Designation names (to reuse
    // exact spelling and avoid accidentally creating a near-duplicate), plus
    // every active employee code (for Reporting Manager / Team Leader).
    try {
      const [deptRes, desigRes, empRes] = await Promise.all([
        db.query(`SELECT name FROM departments ORDER BY name`),
        db.query(`SELECT title, department_id FROM designations ORDER BY title`),
        db.query(`SELECT employee_code, CONCAT(first_name,' ',last_name) AS name FROM employees WHERE is_active=true ORDER BY employee_code`)
      ]);
      const refRows = [
        ['Existing Departments'],
        ...deptRes.rows.map(d => [d.name]),
        [],
        ['Existing Designations'],
        ...desigRes.rows.map(d => [d.title]),
        [],
        ['Existing Employee Codes (for Reporting Manager / Team Leader)', 'Name'],
        ...empRes.rows.map(e => [e.employee_code, e.name])
      ];
      const wsRef = XLSX.utils.aoa_to_sheet(refRows);
      wsRef['!cols'] = [{ wch: 30 }, { wch: 28 }];
      XLSX.utils.book_append_sheet(wb, wsRef, 'Reference');
    } catch (refErr) {
      console.error('[downloadImportTemplate] reference sheet skipped:', refErr.message);
    }

    const instrRows = [
      ['HRMS Employee Import — How to Fill'],
      [''],
      ['• Fields marked * are required: Employee Code, First Name, Email'],
      ['• Department / Designation: type the name. A brand-new department or'],
      ['  designation is created automatically the moment you upload — you do'],
      ['  not need to set it up in the system first.'],
      ['• Reporting Manager / Team Leader: type their Employee Code (e.g. E066).'],
      ['  They must already exist in the system (either already active, or'],
      ['  earlier in the same sheet — rows are processed top to bottom).'],
      ['• Password: leave blank to use the default import password, or set one'],
      ['  per employee (min 8 characters).'],
      ['• Dates: use YYYY-MM-DD format.'],
      ['• Role: employee / tl / manager / hr / accounts / admin (defaults to'],
      ['  employee if blank or invalid).'],
      ['• Saturday Policy: 2nd_4th_off (2nd & 4th Saturday off) or all_working.'],
      ['• Leave any field blank if not applicable — nothing is required beyond'],
      ['  the three starred fields.'],
      ['• Delete the sample row before uploading — it will otherwise be'],
      ['  skipped automatically since its Employee Code (E999) is a duplicate'],
      ['  only if that code already exists; if it doesn\'t, it WILL be created.'],
      ['• New employees are auto-seeded with EL/CL/SL leave balances based on'],
      ['  joining date (or PL only if joined within the last 6 months).'],
    ];
    const wsInstr = XLSX.utils.aoa_to_sheet(instrRows);
    wsInstr['!cols'] = [{ wch: 90 }];
    XLSX.utils.book_append_sheet(wb, wsInstr, 'Instructions');

    const buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', 'attachment; filename="employee_import_template.xlsx"');
    res.send(buf);
  } catch (err) {
    console.error('[downloadImportTemplate]', err);
    res.status(500).json({ success: false, message: 'Server error: ' + err.message });
  }
};
